[project]
name = "AI_ACBP_Translation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-cloud-translate==2.0.1",
    "google-genai>=1.59.0",
    "requests>=2.32.5",
    "tqdm>=4.67.1",
]
